VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false

  (0..2).each do |i|
    config.vm.define "vagrant#{i+1}" do |vagrant|
      vagrant.vm.box = "ubuntu/trusty64"
      vagrant.vm.network "private_network", ip: "192.168.35.1#{i}"
      vagrant.vm.hostname = "vagrant#{i+1}"
    end
  end
end
