VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false
  
  # create mgmt node
  config.vm.define :mgmt, autostart: true do |mgmt_config|
      mgmt_config.vm.box = "centos/7"
      mgmt_config.vm.hostname = "mgmt"
      mgmt_config.vm.network :private_network, ip: "10.0.15.10"
      mgmt_config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
      # mgmt_config.vm.provider "virtualbox" do |vb|
      #   vb.memory = "256"
      # end
      mgmt_config.vm.provision :shell, path: "~/_src/VagrantProjects/ansible_devbox/centos/7/bootstrap-mgmt.sh"
  end

  # config.vm.define "vagrant1" do |vagrant1|
  #   vagrant1.vm.box = "ubuntu/trusty64"
  #   vagrant1.vm.network :private_network, ip: "10.0.15.11"
  #   vagrant1.vm.network "forwarded_port", guest: 80, host: 8080
  #   vagrant1.vm.network "forwarded_port", guest: 443, host: 8443
  # end
  # config.vm.define "vagrant2" do |vagrant2|
  #   vagrant2.vm.box = "ubuntu/trusty64"
  #   vagrant2.vm.network :private_network, ip: "10.0.15.12"
  #   vagrant2.vm.network "forwarded_port", guest: 80, host: 8081
  #   vagrant2.vm.network "forwarded_port", guest: 443, host: 8444
  # end
  # config.vm.define "vagrant3" do |vagrant3|
  #   vagrant3.vm.box = "ubuntu/trusty64"
  #   vagrant3.vm.network :private_network, ip: "10.0.15.13"
  #   vagrant3.vm.network "forwarded_port", guest: 80, host: 8082
  #   vagrant3.vm.network "forwarded_port", guest: 443, host: 8445
  # end
end
