# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # create mgmt node
  config.vm.define :mgmt do |mgmt_config|
      mgmt_config.vm.box = "centos/7"
      mgmt_config.vm.hostname = "mgmt"
      mgmt_config.vm.network :private_network, ip: "10.0.15.10"
      mgmt_config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
      end
      mgmt_config.vm.provision :shell, path: "bootstrap-mgmt.sh"
  end

  # create load balancer
  config.vm.define :zk do |zk_config|
      zk_config.vm.box = "ubuntu/trusty64"
      zk_config.vm.hostname = "zk"
      zk_config.vm.network :private_network, ip: "10.0.15.11"
      zk_config.vm.network "forwarded_port", guest: 80, host: 8080
      zk_config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
      end
  end

  # create some brokers servers
  # https://docs.vagrantup.com/v2/vagrantfile/tips.html
  (1..2).each do |i|
    config.vm.define "broker#{i}", autostart: false do |node|
        node.vm.box = "ubuntu/trusty64"
        node.vm.hostname = "broker#{i}"
        node.vm.network :private_network, ip: "10.0.15.2#{i}"
        node.vm.network "forwarded_port", guest: 80, host: "808#{i}"
        node.vm.provider "virtualbox" do |vb|
          vb.memory = "256"
        end
    end
  end

end
