# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox", create: true
  
  # configure proxy settings if 'vagrant-proxyconf' plugin is intalled
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://192.168.0.2:3128/"
    config.proxy.https    = "http://192.168.0.2:3128/"
    config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
  end

  # create mgmt node
  config.vm.define :mgmt, autostart: true do |mgmt_config|
      mgmt_config.vm.box = "centos/7"
      mgmt_config.vm.hostname = "mgmt"
      mgmt_config.vm.network :private_network, ip: "10.0.15.10"
      mgmt_config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
      mgmt_config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
      end
      mgmt_config.vm.provision :shell, path: "bootstrap-mgmt.sh"
  end

  # create load balancer
  config.vm.define :zk, autostart: false do |zk_config|
      zk_config.vm.box = "centos/7"
      zk_config.vm.hostname = "zk"
      zk_config.vm.network :private_network, ip: "10.0.15.11"
      zk_config.vm.network "forwarded_port", guest: 80, host: 8080
      zk_config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
      end
  end

  # create some brokers servers
  # https://docs.vagrantup.com/v2/vagrantfile/tips.html
  (1..2).each do |i|
    config.vm.define "broker#{i}", autostart: false do |node|
        node.vm.box = "centos/7"
        node.vm.hostname = "broker#{i}"
        node.vm.network :private_network, ip: "10.0.15.2#{i}"
        node.vm.network "forwarded_port", guest: 80, host: "808#{i}"
        node.vm.provider "virtualbox" do |vb|
          vb.memory = "256"
        end
    end
  end

end
